
export const hospitals: string[] = [
    "National Hospital of Sri Lanka",
    "Sri Jayewardenepura General Hospital",
    "Nawaloka Hospital",
    "Asiri Central Hospital",
    "Lanka Hospitals",
    "Durdans Hospital",
    "Hemas Hospital",
    "Teaching Hospital Karapitiya",
    "Teaching Hospital Kandy",
    "Teaching Hospital Anuradhapura",
    "Teaching Hospital Jaffna",
    "Teaching Hospital Batticaloa",
    "Teaching Hospital Kurunegala",
    "Teaching Hospital Rathnapura",
    "General Hospital Colombo South",
    "General Hospital Colombo North",
    "General Hospital Negombo",
    "General Hospital Gampaha",
    "General Hospital Kalutara",
    "General Hospital Matara",
    "General Hospital Galle",
    "General Hospital Hambantota",
    "General Hospital Badulla",
    "General Hospital Monaragala",
    "General Hospital Ampara",
    "General Hospital Polonnaruwa",
    "General Hospital Trincomalee",
    "General Hospital Vavuniya",
    "General Hospital Mannar",
    "General Hospital Kilinochchi",
    "General Hospital Mullaitivu",
    "Lady Ridgeway Hospital for Children",
    "De Soysa Hospital for Women",
    "Castle Street Hospital for Women",
    "National Cancer Institute Maharagama",
    "National Institute of Mental Health",
    "National Eye Hospital Colombo",
    "Chest Hospital Welisara",
    "Rehabilitation Hospital Ragama",
    "Police Hospital Colombo",
    "Army Hospital Colombo",
    "Navy Hospital Colombo",
    "Air Force Hospital Colombo",
    "Base Hospital Avissawella",
    "Base Hospital Balapitiya",
    "Base Hospital Chilaw",
    "Base Hospital Dambulla",
    "Base Hospital Deniyaya",
    "Base Hospital Dikoya",
    "Base Hospital Embilipitiya",
    "Base Hospital Gampola",
    "Base Hospital Hambantota",
    "Base Hospital Homagama",
    "Base Hospital Horana",
    "Base Hospital Kalmunai North",
    "Base Hospital Kalmunai South",
    "Base Hospital Kantale",
    "Base Hospital Kegalle",
    "Base Hospital Kuliyapitiya",
    "Base Hospital Mahiyanganaya",
    "Base Hospital Marawila",
    "Base Hospital Matale",
    "Base Hospital Mawanella",
    "Base Hospital Moneragala",
    "Base Hospital Puttalam",
    "Base Hospital Tangalle",
    "Base Hospital Tellippalai",
    "Base Hospital Theniyaya",
    "Base Hospital Tissamaharama",
    "Base Hospital Vavuniya",
    "Base Hospital Walasmulla",
    "Base Hospital Warakapola",
    "Base Hospital Wathupitiwala",
    "District Hospital Akkarepattu",
    "District Hospital Ambalangoda",
    "District Hospital Ampara",
    "District Hospital Anuradhapura",
    "District Hospital Badulla",
    "District Hospital Balangoda",
    "District Hospital Bandarawela",
    "District Hospital Batticaloa",
    "District Hospital Chavakachcheri",
    "District Hospital Chenkalady",
    "District Hospital Chunnakam",
    "District Hospital Eheliyagoda",
    "District Hospital Hatton",
    "District Hospital Hingurakgoda",
    "District Hospital Jaffna",
    "District Hospital Kalpitiya",
    "District Hospital Kankesanthurai",
    "District Hospital Kayts",
    "District Hospital Point Pedro",
    "District Hospital Polonnaruwa",
    "District Hospital Pottuvil",
    "District Hospital Rikillagaskada",
    "District Hospital Sammanthurai",
    "District Hospital Teldeniya",
    "District Hospital Trincomalee",
    "District Hospital Urumpirai",
    "District Hospital Valvettithurai",
];
