
export const hospitals: string[] = [
    "Air Force Hospital Colombo",
    "Akuressa Divisional Hospital",
    "Akurana Divisional Hospital",
    "Alawwa Divisional Hospital",
    "Ambalangoda Divisional Hospital",
    "Ampara District General Hospital",
    "Anamaduwa Divisional Hospital",
    "Angoda Base Hospital",
    "Ankumbura Divisional Hospital",
    "Arayampathy Divisional Hospital",
    "Aranayake Divisional Hospital",
    "Army Hospital",
    "Army Hospital Colombo",
    "Asiri Central Hospital",
    "Awissawella Base Hospital",
    "Baddegama Divisional Hospital",
    "Badulla Provincial General Hospital",
    "Balangoda Base Hospital",
    "Balapitiya Base Hospital",
    "Bandarawela Divisional Hospital",
    "Base Hospital Angoda",
    "Base Hospital Avissawella",
    "Base Hospital Balapitiya",
    "Base Hospital Chilaw",
    "Base Hospital Dambulla",
    "Base Hospital Deniyaya",
    "Base Hospital Dikoya",
    "Base Hospital Diyatalawa",
    "Base Hospital Elpitiya",
    "Base Hospital Embilipitiya",
    "Base Hospital Gampola",
    "Base Hospital Hambantota",
    "Base Hospital Homagama",
    "Base Hospital Horana",
    "Base Hospital Kalawanchikudi",
    "Base Hospital Kalmunai North",
    "Base Hospital Kalmunai South",
    "Base Hospital Kalmunai South (Asrof Memorial)",
    "Base Hospital Kamburupitiya",
    "Base Hospital Kantale",
    "Base Hospital Kegalle",
    "Base Hospital Kuliyapitiya",
    "Base Hospital Mahiyangana",
    "Base Hospital Marawila",
    "Base Hospital Matale",
    "Base Hospital Mawanella",
    "Base Hospital Medirigiriya",
    "Base Hospital Moneragala",
    "Base Hospital Panadura",
    "Base Hospital Point Pedro",
    "Base Hospital Puttalam",
    "Base Hospital Puttalum",
    "Base Hospital Tangalle",
    "Base Hospital Teldeniya",
    "Base Hospital Telippalai",
    "Base Hospital Thambuttegama",
    "Base Hospital Theniyaya",
    "Base Hospital Tissamaharama",
    "Base Hospital Valachchenai",
    "Base Hospital Vavuniya",
    "Base Hospital Walasmulla",
    "Base Hospital Warakapola",
    "Base Hospital Wathupitiwala",
    "Batticaloa Teaching Hospital",
    "Beruwala Divisional Hospital",
    "Bibile Divisional Hospital",
    "Buttala Divisional Hospital",
    "Castle Street Hospital for Women",
    "Chavakachcheri Base Hospital",
    "Cheddikulam Divisional Hospital",
    "Chest Hospital Welisara",
    "Dambadeniya Divisional Hospital",
    "Dankotuwa Divisional Hospital",
    "De Soysa Hospital for Women",
    "Dehiattakandya Divisional Hospital",
    "Deltota Divisional Hospital",
    "Deniyaya Base Hospital",
    "Deraniyagala Divisional Hospital",
    "Dharga Town Base Hospital",
    "Dickoya Base Hospital",
    "District General Hospital Ampara",
    "District General Hospital Chilaw",
    "District General Hospital Embilipitiya",
    "District General Hospital Gampaha",
    "District General Hospital Hambantota",
    "District General Hospital Kalutara",
    "District General Hospital Kegalle",
    "District General Hospital Kilinochchi",
    "District General Hospital Mannar",
    "District General Hospital Matale",
    "District General Hospital Matara",
    "District General Hospital Monaragala",
    "District General Hospital Mulativu",
    "District General Hospital Nawalapitiya",
    "District General Hospital Negombo",
    "District General Hospital Nuwara Eliya",
    "District General Hospital Polonnaruwa",
    "District General Hospital Trincomalee",
    "District General Hospital Vavuniya",
    "Divisional Hospital Type A - Wijaya Kumarathunga",
    "Divisional Hospital Type B - Pimbura",
    "Divulapitiya Divisional Hospital",
    "Dolosgabe Divisional Hospital",
    "Dompe Divisional Hospital",
    "Durdans Hospital",
    "Eheliyagoda Divisional Hospital",
    "Elyapattuwa Divisional Hospital",
    "Eppawala Divisional Hospital",
    "Eravur Divisional Hospital",
    "Galadedara Divisional Hospital",
    "Galenbindunuwewa Divisional Hospital",
    "Galgamuwa Divisional Hospital",
    "Galnewa Divisional Hospital",
    "Gampola Base Hospital",
    "General Hospital Ampara",
    "General Hospital Badulla",
    "General Hospital Colombo North",
    "General Hospital Colombo South",
    "General Hospital Galle",
    "General Hospital Gampaha",
    "General Hospital Hambantota",
    "General Hospital Kalutara",
    "General Hospital Mannar",
    "General Hospital Matara",
    "General Hospital Monaragala",
    "General Hospital Mullaitivu",
    "General Hospital Negombo",
    "General Hospital Polonnaruwa",
    "General Hospital Trincomalee",
    "General Hospital Vavuniya",
    "Godakawela Divisional Hospital",
    "Gokarella Divisional Hospital",
    "Hasalake Divisional Hospital",
    "Hemmathaga Divisional Hospital",
    "Hemas Hospital",
    "Hingurakgoda Divisional Hospital",
    "Hiripitiya Divisional Hospital",
    "Horowpathana Divisional Hospital",
    "Huruluwewa Divisional Hospital",
    "Ingiriya Divisional Hospital",
    "Kadugannawa Divisional Hospital",
    "Kahatagasdigiliya Divisional Hospital",
    "Kahawatta Divisional Hospital",
    "Kalawana Divisional Hospital",
    "Kaltota Divisional Hospital",
    "Kandana Divisional Hospital",
    "Kankesanthurai District Hospital",
    "Karawanella Divisional Hospital",
    "Kattankudi Divisional Hospital",
    "Katugastota Divisional Hospital",
    "Kayts Base Hospital",
    "Kekirawa Divisional Hospital",
    "Kiriella Divisional Hospital",
    "Kirobathgoda Divisional Hospital",
    "Kitulgala Divisional Hospital",
    "Kolonna Divisional Hospital",
    "Kurunegala Provincial General Hospital",
    "Lady Ridgeway Hospital for Children",
    "Lahugala Divisional Hospital",
    "Lanka Hospitals",
    "Madankadawala Divisional Hospital",
    "Madulkele Divisional Hospital",
    "Maho Divisional Hospital",
    "Mallavi Divisional Hospital",
    "Mampitiya Divisional Hospital",
    "Mankulam Divisional Hospital",
    "Marassana Divisional Hospital",
    "Marawila Divisional Hospital",
    "Maskeliya Divisional Hospital",
    "Matugama Divisional Hospital",
    "Mawarala Divisional Hospital",
    "Mawathagama Divisional Hospital",
    "Medawachchiya Divisional Hospital",
    "Menikhinna Divisional Hospital",
    "Mihintale Divisional Hospital",
    "Minuwangoda Divisional Hospital",
    "Mirigama Divisional Hospital",
    "Mulleriyawa Divisional Hospital",
    "Mulangavil Divisional Hospital",
    "Muthur Divisional Hospital",
    "Naddankandal Divisional Hospital",
    "National Cancer Institute Maharagama",
    "National Eye Hospital Colombo",
    "National Hospital - Kandy",
    "National Hospital of Sri Lanka",
    "National Institute of Mental Health",
    "Nawalapitiya District General Hospital",
    "Nawaloka Hospital",
    "Navy Hospital",
    "Navy Hospital Colombo",
    "Nikaweratiya Divisional Hospital",
    "Nintavur Divisional Hospital",
    "Nivithigala Divisional Hospital",
    "Nochchiyagama Divisional Hospital",
    "Padaviya Base Hospital",
    "Pallebedda Divisional Hospital",
    "Passara Divisional Hospital",
    "Periyakallar Divisional Hospital",
    "Police Hospital Colombo",
    "Polpitigama Divisional Hospital",
    "Pottuvil Divisional Hospital",
    "Provincial General Hospital Badulla",
    "Provincial General Hospital Kurunegala",
    "Pulmoddai Divisional Hospital",
    "Pussellawa Divisional Hospital",
    "Puthukkudiyiruppu Divisional Hospital",
    "Rakwana Divisional Hospital",
    "Rambukkana Divisional Hospital",
    "Rehabilitation Hospital",
    "Rehabilitation Hospital Ragama",
    "Ridigama Divisional Hospital",
    "Rikillagaskada Divisional Hospital",
    "Sandalankawa Divisional Hospital",
    "Sampathnuwara Divisional Hospital",
    "Sammanturai Base Hospital",
    "Sirimavo Bandaranayake Hospital",
    "Siyambalanduwa Divisional Hospital",
    "Sri Jayewardenepura General Hospital",
    "Talawa Divisional Hospital",
    "Tantirimale Divisional Hospital",
    "Teaching Hospital - Dental Institute",
    "Teaching Hospital - Lady Ridgeway Hospital for Children",
    "Teaching Hospital - Welisara",
    "Teaching Hospital Anuradhapura",
    "Teaching Hospital Batticaloa",
    "Teaching Hospital Colombo North Ragama",
    "Teaching Hospital Colombo South Kalubowila",
    "Teaching Hospital Jaffna",
    "Teaching Hospital Kandy",
    "Teaching Hospital Karapitiya",
    "Teaching Hospital Kuliyapitiya",
    "Teaching Hospital Kurunegala",
    "Teaching Hospital Mahamodara",
    "Teaching Hospital Peradeniya",
    "Teaching Hospital Rathnapura",
    "Teaching Hospital Ratnapura",
    "Teldeniya Divisional Hospital",
    "Thirukkovil Divisional Hospital",
    "Thittapajjila Divisional Hospital",
    "Tissamaharama Base Hospital",
    "Udadumbara Divisional Hospital",
    "Udugama Divisional Hospital",
    "Undugoda Divisional Hospital",
    "Valvettithurai District Hospital",
    "Walapane Divisional Hospital",
    "Wallawaya Divisional Hospital",
    "Wariyapola Divisional Hospital",
    "Wattegama Divisional Hospital",
    "Welikanda Divisional Hospital",
    "Welimada Divisional Hospital",
    "Wetara Divisional Hospital",
    "lanka Hospital"
];
